services:
  local-setup:
    build: .
    container_name: local-setup
    ports:
      - "3000:3000"
      - "4006:4006"
      - "3306:3306"
    volumes:
      - /home/ubuntu/local-setup/note-fullstack:/app
    environment:
      - DATABASE_NAME=notes
      - DATABASE_USER=rohit
      - DATABASE_PASSWORD=secret
      - DATABASE_HOST=localhost
