services:
  local-setup:
    build: .
    container_name: local-setup
    ports:
      - "3000:3000"
      - "4006:4006"
    volumes:
      - /home/ubuntu/local-setup/note-fullstack:/app
    environment:
      - DATABASE_NAME=notes
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
      - DATABASE_HOST=dev-database
  dev-database:
    image: belwalrohit642/dev-database:latest
    container_name: dev-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"

