name: Node.js CI

on:
 push:
    branches: [ "master" ]
 pull_request:
    branches: [ "master" ]

jobs:
 build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v4

    # Frontend build and test
    - name: Frontend Build and Test
      run: |
        cd note-fullstack/notes-ui
        npm install react react-dom react-router-dom react-scripts web-vitals --no-cache
        npm install --no-cache
        # Uncomment if you want to run tests
        # npm test

    # Backend build and test
    - name: Backend Build and Test
      run: |
        cd note-fullstack/server
        npm install body-parser cross-env express mocha mysql2 nodemon sequelize should sqlite3 supertest --no-cache
        npm install --no-cache
        # Uncomment if you want to run tests
        # npm test

 build_docker_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Images
      run: |
        docker build -t belwalrohit642/devaction-frontend:${{ github.run_number }} -f note-fullstack/notes-ui/Dockerfile note-fullstack/notes-ui
        docker build -t belwalrohit642/devaction-backend:${{ github.run_number }} -f note-fullstack/server/Dockerfile note-fullstack/server

 push_docker_images:
    needs: build_docker_images
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Push Docker Images
      uses: docker/build-push-action@v2
      with: 
        context: note-fullstack/notes-ui
        file: note-fullstack/notes-ui/Dockerfile
        push: true
        tags: belwalrohit642/devaction-frontend:${{ github.run_number }}

    - name: Push Docker Images
      uses: docker/build-push-action@v2
      with:
        context: note-fullstack/server
        file: note-fullstack/server/Dockerfile
        push: true
        tags: belwalrohit642/devaction-backend:${{ github.run_number }}

 deploy_with_docker_compose:
    needs: push_docker_images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update docker-compose.yaml
      run: |
        echo "Updating docker-compose.yaml with new image tags..."
        sed -i "s|image: belwalrohit642/devaction-frontend:.*|image: belwalrohit642/devaction-frontend:${{ github.run_number }}|" docker-compose.yaml
        sed -i "s|image: belwalrohit642/devaction-backend:.*|image: belwalrohit642/devaction-backend:${{ github.run_number }}|" docker-compose.yaml
    
    - name: Copy docker-compose.yaml to EC2
      uses: appleboy/scp-action@master
      with:
          host: 44.212.44.158
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yaml"
          target: "/home/ubuntu"
    - name: Deploy with Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: 44.212.44.158
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Deploying with Docker Compose..."
          cd /home/ubuntu
          ls -al
          sudo docker-compose up -d
