name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v4

    # Frontend build and test
    - name: Frontend Build and Test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Frontend Code
          uses: actions/checkout@v4
          with:
            path: notes-ui
        - name: Use Node.js ${{ matrix.node-version }} for Frontend
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - name: Build Frontend
          run: npm install react react-dom react-router-dom react-scripts web-vitals --no-cache
          working-directory: notes-ui
        - name: Install Frontend Dependencies
          run: npm install --no-cache
          working-directory: notes-ui
        # Uncomment if you want to run tests
        # - name: Test Frontend
        #   run: npm test
        #   working-directory: notes-ui

    # Backend build and test
    - name: Backend Build and Test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Backend Code
          uses: actions/checkout@v4
          with:
            path: server
        - name: Use Node.js ${{ matrix.node-version }} for Backend
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - name: Build Backend
          run: npm install body-parser cross-env express mocha mysql2 nodemon sequelize should sqlite3 supertest --no-cache
          working-directory: server
        - name: Install Backend Dependencies
          run: npm install --no-cache
          working-directory: server
        # Uncomment if you want to run tests
        # - name: Test Backend
        #   run: npm test
        #   working-directory: server

  build_docker_images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Images
      run: |
        docker build -t belwalrohit642/devaction-frontend:${{ github.run_number }} -f notes-ui/Dockerfile notes-ui
        docker build -t belwalrohit642/devaction-backend:${{ github.run_number }} -f server/Dockerfile server
