name: Node.js CI

on:
 push:
    branches: [ "master" ]
 pull_request:
    branches: [ "master" ]

jobs:
 build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v4

    # Frontend build and test
    - name: Frontend Build and Test
      run: |
        cd note-fullstack/notes-ui
        npm install react react-dom react-router-dom react-scripts web-vitals --no-cache
        npm install --no-cache
        # Uncomment if you want to run tests
        # npm test

    # Backend build and test
    - name: Backend Build and Test
      run: |
        cd note-fullstack/server
        npm install body-parser cross-env express mocha mysql2 nodemon sequelize should sqlite3 supertest --no-cache
        npm install --no-cache
        # Uncomment if you want to run tests
        # npm test

 build_docker_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Images
      run: |
        docker build -t belwalrohit642/devaction-frontend:${{ github.run_number }} -f note-fullstack/notes-ui/Dockerfile note-fullstack/notes-ui
        docker build -t belwalrohit642/devaction-backend:${{ github.run_number }} -f note-fullstack/server/Dockerfile note-fullstack/server
